version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app:rodo
    # env_file:
    #   - .env
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=postgres
      - SECRET_KEY={SECRET_KEY}
      - ALGORITHM={ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES={ACCESS_TOKEN_EXPIRE_MINUTES}
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=Navkar96
      - POSTGRES_DB=Item_details
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
